{{-- =====================================================================
Global UI State — Alpine.store('ui') for shared darkMode, lang, t()
Wrap your page content with <x-ui-state> ... </x-ui-state>
===================================================================== --}}
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.store('ui', {
            darkMode: false,
            lang: 'English',
            loading: false,

            showLoading(ms = 800) {
                this.loading = true;
                setTimeout(() => { this.loading = false; }, ms);
            },

            /* -- i18n translation map -- */
            t(key) {
                const dict = {
                    English: {
                        /* Hero */
                        heroHeadline1: 'Manage internships with',
                        heroHeadline2: 'confidence using InternDesk',
                        heroSubtitle: 'The preferred platform for organizations that invest in future talent.',
                        heroPlaceholder: 'Enter your email',
                        heroTryFree: 'Try for free',
                        heroPrivacy: 'By submitting, I agree to InternDesk\'s',
                        heroPrivacyLink: 'Privacy Notice',
                        heroInvalidEmail: 'Please enter a valid email address.',
                        heroThankYou: 'Thank you! Check your email.',
                        heroDashboard: 'Go to Dashboard',

                        /* Discover */
                        discoverBadge1: 'Users Love Us',
                        discoverBadge2: 'Happiest Users 2023',
                        discoverTitle: 'Discover InternDesk',
                        discoverTab_ticketList: 'Application list',
                        discoverTab_ticketView: 'Application view',
                        discoverTab_automations: 'Automations',
                        discoverTab_reports: 'Reports',
                        discoverCta: 'Sign up free',

                        /* Support Heroes */
                        heroesTitle1: 'We\'re here for you',
                        heroesTitle2: '24/7/365',
                        heroesDescription: 'When you need assistance, you can count on our InternDesk Heroes. They\'re strong, they\'re swift, and they\'ll help you no matter the time!',
                        heroesCta: 'Chat with us',
                        homeSupportHeroesBadge: 'InternDesk Heroes',
                        homeSlaCardTitle: 'Deadline Tracking',
                        homeSlaCardBody: 'Live countdown timers on every application. Amber warnings, red alerts on overdue items.',
                        homeKnowledgeCardTitle: 'Resource Center',
                        homeKnowledgeCardBody: 'A full public resource center at your subdomain — guides, policies, and search.',
                        homeGetStartedHeading: 'Get Started',
                        homeGetStartedLine1: 'Learn the platform in less than an hour.',
                        homeGetStartedLine2Prefix: 'Become a',
                        homeGetStartedLine2Emphasis: 'power user',
                        homeGetStartedLine2Suffix: 'in less than a day.',
                        homeGetStartedPrimaryCta: 'Get Started',
                        homeGetStartedSecondaryCta: 'Book a Demo',
                        homeSfsTitle: 'Plus, all the features internship teams love',
                        homeSfsAutomationTitle: 'Automation Engine',
                        homeSfsAutomationBody: 'Set conditions once — applications route, escalate, and notify automatically.',
                        homeSfsTagsTitle: 'Tags & Labels',
                        homeSfsTagsBody: 'Organize every application with color-coded tags so nothing falls through the cracks.',
                        homeSfsInboxesTitle: 'Multiple Departments',
                        homeSfsInboxesBody: 'Give every department or program its own dedicated space for internship management.',
                        homeSfsAiTitle: 'AI Copilot',
                        homeSfsAiBody: 'AI reads the application, suggests a response in your tone, and summarizes the full history.',
                        homeSfsReportsTitle: 'Analytics & Reports',
                        homeSfsReportsBody: 'Track team performance, placement rates, and intern satisfaction at a glance.',
                        homeSfsRoutingTitle: 'Smart Matching',
                        homeSfsRoutingBody: 'Every application finds the best available supervisor instantly — based on department and workload.',
                        homeSfsPreviewAutomationRule: 'Automation Rule',
                        homeSfsPreviewActive: 'Active',
                        homeSfsPreviewWhen: 'WHEN',
                        homeSfsPreviewThen: 'THEN',
                        homeSfsPreviewAssignTo: 'Assign to',
                        homeSfsPreviewBillingTeam: 'Engineering Dept',
                        homeSfsPreviewRanTimes: 'Ran 248 times',
                        homeSfsPreviewAiCustomerMsg: 'My internship application #4821 has no response yet. Can you help?',
                        homeSfsPreviewAiSuggestion: 'AI Suggestion',
                        homeSfsPreviewUseReply: 'Use reply',
                        homeSfsPreviewRegenerate: 'Regenerate',
                        homeSfsPreviewTicketQueue: 'Application Queue',
                        homeSfsPreviewBreached: 'Overdue',
                        homeSfsPreviewPaymentFailed: 'Placement delayed',
                        homeSfsPreviewSlaBreachedUrgent: 'Deadline passed · Urgent',
                        homeSfsPreviewKbSearch: 'Search resource center...',
                        homeSfsPreviewKbArticle1: 'How to submit your internship report',
                        homeSfsPreviewKbMeta1: 'Reports · 2 min read',
                        homeSfsPreviewKbArticle2: 'Reset your intern portal password',
                        homeSfsPreviewKbMeta2: 'Account · 1 min read',
                        homeSfsPreviewKbArticle3: 'Tracking your placement status',
                        homeSfsPreviewKbMeta3: 'Placements · 3 min read',
                        homeSfsPreviewKbBadge: '24 articles · Available at /resources',
                        homeSfsPreviewReportsHead: 'Team Performance · This Week',
                        homeBeaconAiAssistant: 'AI Assistant',
                        homeBeaconEndChat: 'End chat',
                        homeBeaconAskQuestion: 'Ask a question...',
                        homeBeaconAgentsOnline: '2 coordinators online',
                        homeBeaconPreviousConversations: 'Previous Conversations',
                        homeBeaconLastUpdatedToday: 'Last updated today',
                        homeSfsTagResolved: 'Completed',
                        homeSfsTagPending: 'In Progress',
                        homeSfsTagBug: 'Issue',
                        homeSfsTagGeneral: 'General',
                        homeSfsTagOnboarding: 'Onboarding',
                        homeSfsPreviewFriendly: 'Friendly',
                        homeSfsPreviewFormal: 'Formal',
                        homeSfsPreviewCantLogin: 'Can\'t access portal',
                        homeSfsPreviewMinutesLeftHigh: '18 min left · High',
                        homeSfsPreviewAvgReply: 'Avg Reply',
                        homeSfsPreviewResolved: 'Completed',
                        homeSfsPreviewUrgent: 'Urgent',
                        homeSfsPreviewAccount2fa: 'Can\'t access intern portal after 2FA',
                        homeSfsPreviewCategoryAccount: 'Department: Engineering',
                        homeSfsPreviewAssignedSara: 'Assigned to Sara K.',
                        homeSfsPreviewAccountTeamTickets: 'Engineering Team · 2 open applications',
                        homeSfsPreviewRoutedIn: 'Routed in',
                        homeBeacon3Billing: 'Placement',
                        homeBeacon3SlaBreachSoon: 'Deadline in 18 min - respond now',
                        homeBeacon3CustomerSarah: 'Intern · Sarah M.',
                        homeBeacon3CustomerMessage: 'Hi, my internship placement hasn\'t been confirmed yet and the start date is next week.',
                        homeBeacon3AgentReply: 'Hi Sarah, I\'ve confirmed your placement with the Engineering department. Your supervisor will reach out with onboarding details shortly.',
                        homeBeacon3Tone: 'Tone:',
                        homeBeacon3Professional: 'Professional',
                        homeBeacon3OpenBreached: 'open · 2 overdue',
                        homeBeacon3FilterAll: 'All',
                        homeBeacon3FilterUnassigned: 'Unassigned',
                        homeBeacon3NoAccountNeeded: 'No account needed — just your email',
                        homeBeacon3StepSubmitted: 'Application submitted',
                        homeBeacon3StepAssigned: 'Assigned to coordinator',
                        homeBeacon3StepInProgress: 'In progress',
                        homeBeacon3ReplyToAgent: 'Reply to coordinator',

                        /* Beacons */
                        beacon1Title: 'Meet InternDesk AI: your internship management hub',
                        beacon1Tab1Title: 'Answer instantly with AI',
                        beacon1Tab1Body: 'Let AI handle common intern questions around the clock — no wait time, no coordinator needed.',
                        beacon1Tab2Title: 'Keep human guidance within reach',
                        beacon1Tab2Body: 'Whether you offer live chat, email, or both, your coordinators will always be within two clicks.',
                        beacon1Tab3Title: 'Save interns time',
                        beacon1Tab3Body: 'Allow easy access to previous conversations so interns can pick up where they left off.',
                        beacon1DemoMsg1: 'Hi! I can answer your questions instantly. What do you need help with?',
                        beacon1DemoMsg2: 'What\'s the internship onboarding process?',
                        beacon1DemoMsg3: 'Once your placement is confirmed, you\'ll receive an onboarding kit with supervisor details and your schedule within 48 hours! 🎓',
                        beacon1DemoHuman1: 'Hey Amber! Nikita here. What can I help you with today?',
                        beacon1DemoHuman2: 'Hi there! I\'m wondering about the status of my internship application.',
                        beacon1DemoHuman3: 'The application number is #10283089',
                        beacon2Title: 'Stay organized automatically',
                        beacon2Tab1Title: 'Match the right supervisor',
                        beacon2Tab1Body: 'Automatically route each application to the supervisor best suited to mentor the intern.',
                        beacon2Tab2Title: 'Never miss important deadlines',
                        beacon2Tab2Body: 'Keep urgent internship matters visible with clear priorities and smart alerts.',
                        beacon2Tab3Title: 'Simplify the queue for your team',
                        beacon2Tab3Body: 'Help everyone get more efficient with custom views that group applications by department.',
                        beacon3TitlePrefix: 'Everything your internship team needs',
                        beacon3TitleEmphasis: 'in one place',
                        beacon3Tab1Title: 'AI Copilot for every coordinator',
                        beacon3Tab1Body: 'AI reads the full application, generates a suggested response in your chosen tone, and summarizes the entire history so coordinators move faster without missing context.',
                        beacon3Tab2Title: 'Smart matching, live deadline tracking',
                        beacon3Tab2Body: 'Every application is auto-assigned to the best available coordinator, while deadline countdowns and overdue alerts keep response times on track.',
                        beacon3Tab3Title: 'Zero friction for interns',
                        beacon3Tab3Body: 'No account needed. Interns verify by email, receive a tracking link, and follow updates or reply from any device.',

                        /* Navbar */
                        products: 'Products',
                        solutions: 'Solutions',
                        resources: 'Resources',
                        pricing: 'Pricing',
                        companyMenu: 'Company',
                        tryFree: 'Sign up free',
                        viewDemo: 'Login',
                        dashboard: 'Dashboard',
                        platform: 'Platform',
                        platformOverview: 'Platform overview',
                        integrations: 'Integrations',
                        latestInnovations: 'Latest innovations',
                        appMarketplace: 'App marketplace',
                        developers: 'Developers',
                        trending: 'Trending',
                        trendItem1: 'InternDesk Summit 2026',
                        trendDesc1: 'A global event for leaders in HR, internships, and talent.',
                        trendItem2: 'Hidden costs of manual tracking',
                        trendDesc2: 'Uncover the complexity tax costing your internship program.',
                        trendItem3: 'InternDesk partners with top universities',
                        trendDesc3: 'Discover how InternDesk powers global internship partnerships.',
                        navProductFeatureTitle: 'Meet InternDesk AI',
                        navProductFeatureBadge: 'NEW',
                        navProductFeatureDescription: 'Agentic AI that reasons, acts and resolves',
                        navProductFeatureCta: 'Explore InternDesk AI',
                        productCard1Title: 'Placement Manager',
                        productCard1Desc: 'Modern internship placement and tracking.',
                        productCard2Title: 'InternDesk Omni',
                        productCard2Desc: 'Omnichannel intern communication powered by AI.',
                        productCard3Title: 'InternDesk Lite',
                        productCard3Desc: 'Simple internship management for growing teams.',
                        productLearnMore: 'Learn more',
                        productFeatured: 'Featured',
                        productTour: 'Product tour',
                        productTourDesc1: 'See how teams manage placements faster.',
                        productTourDesc2: 'Explore automation for every internship workflow.',
                        productTourDesc3: 'Discover a faster application process in minutes.',
                        productWhatsNew: 'What\'s new',
                        productUpdateDesc: 'Latest AI improvements and integrations.',
                        productAllTrials: 'View all product trials',
                        companyAbout: 'About us',
                        companyAboutDesc: 'Learn our mission, story, and values.',
                        companyCareers: 'Careers',
                        companyCareersDesc: 'Build products that help teams manage talent better.',
                        companyHelpCenterDesc: 'Browse guides, FAQs, and platform resources.',
                        companyContactDesc: 'Reach our team for sales or platform questions.',
                        companyPartnerDesc: 'Grow with our global partner network.',
                        navResourceFeatureTitle: 'Learn with practical resources',
                        navResourceFeatureDescription: 'Playbooks, docs, and guides to launch better internship workflows.',
                        navResourceFeatureCta: 'Explore resources',
                        byTeam: 'By Team',
                        customerService: 'HR Operations',
                        itSupport: 'IT Support',
                        hrTeams: 'HR Teams',
                        salesTeams: 'Talent Acquisition',
                        bySize: 'By Company Size',
                        enterprise: 'Enterprise',
                        midMarket: 'Mid-market',
                        smallBusiness: 'Small Business',
                        startups: 'Startups',
                        learn: 'Learn',
                        blog: 'Blog',
                        documentation: 'Documentation',
                        webinars: 'Webinars',
                        academy: 'Academy',
                        connect: 'Connect',
                        community: 'Community',
                        events: 'Events',
                        partnerProgram: 'Partner program',
                        support: 'Support',

                        /* Utility Bar */
                        utilitySignIn: 'Sign in',
                        utilityLogout: 'Logout',
                        utilityHelpCenter: 'Help Center',
                        utilityCompany: 'Company',
                        utilityContactUs: 'Contact us',

                        /* Footer */
                        footerTagline: 'Modern internship management for modern teams.',
                        footerProducts: 'Products',
                        footerPlatformOverview: 'Platform Overview',
                        footerIntegrations: 'Integrations',
                        footerMarketplace: 'App Marketplace',
                        footerDevelopers: 'Developers',
                        footerSolutions: 'Solutions',
                        footerCustomerService: 'HR Operations',
                        footerItSupport: 'IT Support',
                        footerHrTeams: 'HR Teams',
                        footerSalesTeams: 'Talent Acquisition',
                        footerResources: 'Resources',
                        footerBlog: 'Blog',
                        footerDocumentation: 'Documentation',
                        footerWebinars: 'Webinars',
                        footerCommunity: 'Community',
                        footerCompany: 'Company',
                        footerAbout: 'About Us',
                        footerCareers: 'Careers',
                        footerContact: 'Contact',
                        footerPrivacy: 'Privacy Policy',
                        footerRights: 'All rights reserved.',
                        footerColProduct: 'Product',
                        footerLinkDashboard: 'Dashboard',
                        footerLinkFeatures: 'Features',
                        footerLinkDiscover: 'Discover',
                        footerLinkFooter: 'Footer',
                        footerColResources: 'Resources',
                        footerLinkGettingStarted: 'Getting Started',
                        footerLinkAutomationIdeas: 'Workflow Ideas',
                        footerLinkCustomerStories: 'Success Stories',
                        footerLinkBrandAssets: 'Brand Assets',
                        footerColQuickLinks: 'Quick Links',
                        footerLinkHome: 'Home',
                        footerLinkProductTour: 'Product Tour',
                        footerLinkTestimonials: 'Testimonials',
                        footerLinkFooterLayout: 'Footer Layout',
                        footerColCompanySupport: 'Company & Support',
                        footerLinkAbout: 'About',
                        footerLinkHelpCenter: 'Help Center',
                        footerLinkContact: 'Contact',
                        footerLinkStatus: 'Status',
                        footerBrand: 'InternDesk',

                        /* Notification banner */
                        notificationBannerLine: 'We\'d love to help. Talk to our',
                        notificationBannerStrong: 'InternDesk team.',
                        notificationBannerCta: 'Chat now ->',
                        notificationBannerDismiss: 'Dismiss notification',

                        /* Chatbot widget */
                        chatbotWelcome1: 'Welcome to InternDesk! We\'re here to assist you with any questions about your internship. How can we help you today?',
                        chatbotWelcome2: 'Hello there! Need a hand with your internship? We\'re ready to help you right away.',
                        chatbotWelcome3: 'Welcome back! We\'ve been expecting you. What can our internship team do for you today?',
                        chatbotWelcome4: 'Hi! Thanks for reaching out. Let us know how we can help with your internship journey.',
                        chatbotWelcome5: 'Greetings! We\'re here to provide you with fast and friendly internship support. What\'s on your mind?',
                        chatbotNoConversationsTitle: 'No conversations yet',
                        chatbotNoConversationsBody: 'Tap below to start a conversation.<br>We\'ll help you right away!',
                        chatbotStartedPrefix: 'Started',
                        chatbotEnded: 'Ended',
                        chatbotRemoveConversation: 'Remove conversation',
                        chatbotNewConversation: 'New conversation',
                        chatbotBuiltWith: 'BUILT WITH INTERNDESK AI',
                        chatbotRepliesFast: 'Typically replies instantly',
                        chatbotQuickActions: 'Quick actions',
                        chatbotQuickReply1: 'How does the internship application work?',
                        chatbotQuickReply2: 'Can I try it for free?',
                        chatbotQuickReply3: 'What integrations do you support?',
                        chatbotQuickReply4: 'Tell me about pricing',
                        chatbotInputPlaceholder: 'Type your message...',

                        /* About page */
                        aboutTypewriter: 'About us',
                        aboutHeroTitle: 'Building internship software that feels human at scale',
                        aboutHeroDescription: 'InternDesk was created to remove chaos from internship management. We built one platform where teams can route applications intelligently, respond with AI-assisted speed, and manage every placement with confidence.',
                        aboutHeroCtaPrimary: 'Talk to our team',
                        aboutHeroCtaSecondary: 'Explore help center',
                        aboutPillar1Title: 'Global reach',
                        aboutPillar1Body: 'Teams across every timezone trust InternDesk to keep internship operations running.',
                        aboutPillar2Title: 'Built for scale',
                        aboutPillar2Body: 'Enterprise-grade architecture designed from day one for growth.',
                        aboutPillar3Title: 'Privacy first',
                        aboutPillar3Body: 'Your data stays yours with strict isolation and full transparency.',
                        aboutPillar4Title: 'Human-centered',
                        aboutPillar4Body: 'AI that empowers coordinators, never replaces the human connection.',
                        aboutStoryTitle: 'Our story',
                        aboutStoryBody1: 'We started with one observation: HR teams were managing internship programs across disconnected inboxes, spreadsheets, and fragile workflows. Applications were delayed, ownership was unclear, and leaders had no reliable visibility. So we reimagined internship management as a single operating system.',
                        aboutStoryBody2: 'Today, organizations launch InternDesk in hours, not months. Admins define departments, deadlines, automation rules, and team groups. Coordinators get contextual AI suggestions and instant application summaries. Interns receive updates without account friction. Every action is auditable, measurable, and built for scale.',
                        aboutDifferenceTitle: 'What makes InternDesk different',
                        aboutDifference1Title: 'Multi-tenant isolation',
                        aboutDifference1Body: 'Each organization has its own subdomain, data scope, and configuration model with strict separation by design.',
                        aboutDifference2Title: 'No-login intern experience',
                        aboutDifference2Body: 'Interns verify by email and continue through a tracking link, reducing drop-off and friction.',
                        aboutDifference3Title: 'Smart matching engine',
                        aboutDifference3Body: 'Applications route by department, program, specialties, workload, and availability in near real time.',
                        aboutDifference4Title: 'AI as copilot, not replacement',
                        aboutDifference4Body: 'Coordinators stay in control while AI handles summaries, suggestions, and repetitive drafting tasks.',
                        aboutGrowthTitle: 'How teams grow with us',
                        aboutGrowthPhase1Label: 'Phase 1',
                        aboutGrowthPhase1Title: 'Launch in days',
                        aboutGrowthPhase1Body: 'Admins run onboarding, configure departments and deadline policies, then embed the application widget with one script.',
                        aboutGrowthPhase2Label: 'Phase 2',
                        aboutGrowthPhase2Title: 'Automate operations',
                        aboutGrowthPhase2Body: 'Rules assign applications, trigger alerts, and escalate deadline risks automatically while leaders monitor live dashboards.',
                        aboutGrowthPhase3Label: 'Phase 3',
                        aboutGrowthPhase3Title: 'Optimize performance',
                        aboutGrowthPhase3Body: 'Teams refine workflows through analytics, department health reports, and coordinator leaderboards that expose bottlenecks quickly.',
                        aboutNoteTitle: 'A note from our team',
                        aboutNoteBody1: 'We design InternDesk to feel clear, fast, and dependable from day one. We care about operational details: handoff quality, response consistency, escalation visibility, and long-term maintainability. Your internship team should never feel held back by tooling. It should feel amplified.',
                        aboutNoteBody2: 'Whether you are launching your first internship program or scaling a multi-region talent operation, our product and success teams are here to help you build workflows that last.',
                        aboutVisionTitle: 'Deep product vision',
                        aboutVisionBody1: 'We believe internship platforms should not just track applications, but coordinate outcomes. That means every interaction needs structured context, clear ownership, actionable timelines, and measurable quality signals. In InternDesk, every application is tied to departments, priorities, deadline clocks, and operational matching logic so teams can move fast without losing precision.',
                        aboutVisionBody2: 'As application volume grows, complexity grows faster than headcount. We designed InternDesk to absorb that complexity through smart defaults and configurable automation. Assignment rules, escalation triggers, deadline alerts, and lifecycle actions work together so teams spend less time orchestrating work manually and more time mentoring interns.',
                        aboutVisionBody3: 'We also care deeply about experience quality for every role. Admins need control and visibility. Coordinators need speed and context. Interns need frictionless progress. This is why we built no-login application tracking, AI copilot summaries, in-thread collaboration notes, and resource tools into a single workflow that remains clear even under pressure.',
                        aboutInfrastructureTitle: 'How we design internship infrastructure',
                        aboutInfrastructure1Title: 'Reliability first',
                        aboutInfrastructure1Body: 'Workflows are designed for predictable execution. Assignment, escalation, notification, and closure logic run in a deterministic sequence so teams can trust the system in high-volume periods.',
                        aboutInfrastructure2Title: 'Coordinator efficiency',
                        aboutInfrastructure2Body: 'Coordinators see context instantly through AI summaries, clear application states, and direct access to resource center references. This reduces response time and minimizes unnecessary back-and-forth.',
                        aboutInfrastructure3Title: 'Visible outcomes',
                        aboutInfrastructure3Body: 'Leadership gets full operational insight through report views, deadline health, department-level trends, and export-ready datasets that support both daily triage and quarterly planning.',
                        aboutCultureTitle: 'Inside our global internship culture',
                        aboutCultureBody: 'We operate as one distributed team across regions, with shared quality standards and local execution flexibility. Our product, success, and engineering groups collaborate continuously on coordination playbooks, workflow templates, and resource architecture so organizations receive consistent internship outcomes regardless of timezone.',
                        aboutCommitmentTitle: 'Our commitment',
                        aboutCommitmentBody1: 'We commit to building internship software that remains fast, observable, and adaptable as your organization grows. We ship features that reduce operational drag, not just add interface complexity. Every release is evaluated against real internship workflows: application ownership, response quality, queue health, and intern satisfaction.',
                        aboutCommitmentBody2: 'We commit to transparency in how automation runs and how AI suggestions are generated in context. Teams should be able to understand and control the system, not guess at its behavior. That is why we emphasize explicit conditions, clear rule outcomes, and robust reporting across applications, departments, coordinators, and deadline performance.',
                        aboutCommitmentBody3: 'We commit to partnership. Our team supports implementation strategy, migration planning, and long-term optimization so your internship operation can continuously improve over time, not only at launch.',

                        /* Contact page */
                        contactTypewriter: 'Contact',
                        contactHeroTitle: 'Let us help you launch better internship programs faster',
                        contactHeroDescription: 'Tell us what you need, and our team will guide you through setup, migration, automation strategy, and portal embedding.',
                        contactFormTitle: 'Send a message',
                        contactFormRequiredNote: 'Fields marked with * are required.',
                        contactSuccessMessage: 'Message sent successfully. We will get back to you shortly.',
                        contactFieldName: 'Full name *',
                        contactFieldNamePlaceholder: 'Jane Doe',
                        contactFieldEmail: 'Work email *',
                        contactFieldEmailPlaceholder: 'jane@company.com',
                        contactFieldCompany: 'Organization name *',
                        contactFieldCompanyPlaceholder: 'Acme Inc',
                        contactFieldTeamSize: 'Team size',
                        contactTeamSizeOption0: 'Select an option',
                        contactTeamSizeOption1: '1-5 coordinators',
                        contactTeamSizeOption2: '6-20 coordinators',
                        contactTeamSizeOption3: '21-50 coordinators',
                        contactTeamSizeOption4: '50+ coordinators',
                        contactFieldTopic: 'Topic *',
                        contactTopicOption0: 'Choose a topic',
                        contactTopicOption1: 'Book a product demo',
                        contactTopicOption2: 'Migration and onboarding',
                        contactTopicOption3: 'Pricing and plans',
                        contactTopicOption4: 'Technical support',
                        contactFieldMessage: 'Message *',
                        contactFieldMessagePlaceholder: 'Tell us about your internship goals, application volume, and current workflow.',
                        contactResponseNote: 'We respond within one business day.',
                        contactSubmit: 'Send message',
                        contactSalesTitle: 'Talk to sales',
                        contactSalesBody: 'For pricing and implementation planning.',
                        contactSupportTitle: 'Platform support',
                        contactSupportBody: 'Existing users can get fast help from our support team.',
                        contactChecklistTitle: 'Fast start checklist',
                        contactChecklist1: '1. Share your current intern volume and departments.',
                        contactChecklist2: '2. We map departments, deadlines, and automation rules.',
                        contactChecklist3: '3. Your portal goes live with one script tag.',
                        contactOfficesTitle: 'Our offices around the world',
                        contactWhyTitle: 'Why teams contact us before launching',
                        contactWhyBody1: 'Most teams reach out when they are replacing fragmented internship workflows and need a reliable rollout plan. We help define priority matrices, queue ownership, and escalation boundaries before your first live application. This avoids rework after launch and gives coordinators a cleaner, more confident first week in production.',
                        contactWhyBody2: 'We also map your intern journey end-to-end: application points, response templates, auto-replies, deadline thresholds, and completion policy. The result is an internship operation that feels consistent across departments and clear to every stakeholder from day one.',
                        contactAfterTitle: 'What happens after you reach out',
                        contactAfter1Title: 'Discovery call',
                        contactAfter1Body: 'We review your departments, expected volume, team structure, and response targets to design a practical rollout.',
                        contactAfter2Title: 'Configuration plan',
                        contactAfter2Body: 'Departments, deadlines, automation rules, and portal branding are prepared to match your exact workflow.',
                        contactAfter3Title: 'Go-live support',
                        contactAfter3Body: 'We stay with your team through launch, monitor first applications, and tune matching or response flows where needed.',

                        /* Help center page */
                        helpTypewriter: 'Help Center',
                        helpHeroTitle: 'Answers for admins, coordinators, and interns in one place',
                        helpHeroDescription: 'Learn how InternDesk handles application routing, AI copilot, deadline automation, embeddable portals, and reporting workflows.',
                        helpSearchLabel: 'Search answers',
                        helpSearchPlaceholder: 'Try: deadlines, automation, chatbot, application routing',
                        helpPopularAnswersTitle: 'Popular answers',
                        helpShowMoreAnswers: 'Show 10 more answers',
                        helpJourneyTitle: 'Application journey',
                        helpJourney1: '1. Intern submits application via portal.',
                        helpJourney2: '2. Automation routes to department + best coordinator.',
                        helpJourney3: '3. Coordinator receives AI summary and suggestion.',
                        helpJourney4: '4. Placement confirmed, onboarding begins.',
                        helpRoleWorkflowsTitle: 'Role-based workflows',
                        helpRoleAdmin: 'Admin: setup departments, deadlines, groups, and rules.',
                        helpRoleAgent: 'Coordinator: handle queue, notes, replies, and resource links.',
                        helpRoleCustomer: 'Intern: verify email and track without login.',
                        helpAssistanceTitle: 'Need direct assistance?',
                        helpAssistanceBody: 'For account setup, migration, and custom workflows, reach our team.',
                        helpAssistancePrimaryCta: 'Contact team',
                        helpAssistanceSecondaryCta: 'Email support',
                        helpLifecycleTitle: 'Complete internship lifecycle in one platform',
                        helpLifecycleBody1: 'InternDesk is designed to handle the full journey from application to completion. New applications enter through your branded portal, get categorized and prioritized, route to the right department, and receive action in minutes. Coordinators collaborate with private notes, AI suggestions, and resource references while interns stay updated through email and tracking links. Once placed, the lifecycle continues with evaluation windows, progress reports, and completion tracking that keep your data clean and searchable.',
                        helpLifecycleBody2: 'This approach reduces operational fragmentation. Instead of jumping between tools for routing, collaboration, deadline visibility, and intern communication, every team role works in one place with consistent state and a shared source of truth.',
                        helpPlaybooksTitle: 'Operational playbooks for every role',
                        helpPlaybookAdminTitle: 'Admin playbook',
                        helpPlaybookAdminBody: 'Configure departments, deadline tiers, assignment rules, and notification policies. Monitor overdue items live and optimize team throughput from centralized reports.',
                        helpPlaybookAgentTitle: 'Coordinator playbook',
                        helpPlaybookAgentBody: 'Pick from priority-sorted queues, review AI context summary, compose response with optional suggestions, attach files, insert resource links, and confirm placement with confidence.',
                        helpPlaybookCustomerTitle: 'Intern playbook',
                        helpPlaybookCustomerBody: 'Submit application without signup, verify by email, follow progress from tracking link, reply from inbox, and receive clear updates throughout each status change.',
                        helpFaq1Q: 'How does the intern application work without login?',
                        helpFaq1A: 'Interns submit an application from the portal widget, verify their email, and receive a tracking link. They can follow updates and reply directly from that flow without creating an account.',
                        helpFaq2Q: 'How are applications routed to the right coordinators?',
                        helpFaq2A: 'The automation engine applies rules using department, program, priority, assigned group, and availability. Then it picks the most suitable coordinator based on specialties and workload.',
                        helpFaq3Q: 'What does AI Copilot do for coordinators?',
                        helpFaq3A: 'AI reads the full application, generates a concise summary, and suggests editable replies in the selected tone. Coordinators can regenerate, refine, or dismiss suggestions instantly.',
                        helpFaq4Q: 'How does deadline tracking prevent missed dates?',
                        helpFaq4A: 'Each application gets a due time by priority policy. Live countdowns show risk status, and overdue notifications are sent to assigned coordinators and admins when thresholds are hit.',
                        helpFaq5Q: 'Can administrators configure automation without code?',
                        helpFaq5A: 'Yes. Admins create condition-action rules from a visual setup panel. They can assign coordinators/groups, adjust priority, trigger auto-replies, and escalate based on deadline or VIP rules.',
                        helpFaq6Q: 'What lifecycle automation happens after placement confirmation?',
                        helpFaq6A: 'Confirmed placements trigger intern notifications, evaluation reminders, and progress report schedules. Completed internships archive automatically with full history preserved.',
                        helpFaq7Q: 'How does the resource center help coordinators and interns?',
                        helpFaq7A: 'Interns can browse/search public articles under /resources. Coordinators can search resource content directly in application reply tools and insert links without leaving the conversation.',
                        helpFaq8Q: 'Which portals can be embedded on our website?',
                        helpFaq8A: 'InternDesk provides an Application Portal, AI Chatbot Widget, and Resource Search Widget. Each uses script-based embed codes and is managed from one integrations area.',
                        helpFaq9Q: 'How is data isolated in multi-tenant mode?',
                        helpFaq9A: 'Every organization runs in its own subdomain and scoped dataset. Applications, interns, settings, and analytics remain isolated with no cross-organization access.',
                        helpFaq10Q: 'What reports are available for performance analysis?',
                        helpFaq10A: 'Reports include overview trends, coordinator performance, application analysis, and department health. Teams can export insights to CSV/PDF and monitor leaderboard and placement behavior.',
                        helpFaq11Q: 'Can coordinators bulk update multiple applications at once?',
                        helpFaq11A: 'Yes. Coordinators and admins can bulk assign supervisors, change status, adjust priority, and perform batch actions from filtered list views to speed up queue maintenance.',
                        helpFaq12Q: 'How do saved views work for repetitive queue filters?',
                        helpFaq12A: 'Any advanced filter combination can be saved as a named view. Teams can reopen those views instantly to track departments, overdue queues, or coordinator-specific workloads.',
                        helpFaq13Q: 'How are internal notes separated from intern replies?',
                        helpFaq13A: 'Internal notes are stored in the same application timeline but marked as private. They are visible to coordinators/admins only and never sent to interns.',
                        helpFaq14Q: 'Can we use role-based permissions across teams?',
                        helpFaq14A: 'Yes. Admins can control coordinator capabilities, restrict sensitive actions, and scope access by role or group to keep operations consistent and secure.',
                        helpFaq15Q: 'How does priority intern routing work?',
                        helpFaq15A: 'Priority conditions can trigger urgency overrides, specific routing groups, and custom notifications so high-priority applications receive faster and more specialized handling.',
                        helpFaq16Q: 'Can we customize application fields in the portal?',
                        helpFaq16A: 'Admins can configure visible fields, required flags, department/program controls, phone requirements, and default values from the portal settings panel.',
                        helpFaq17Q: 'What happens if no coordinator is available at application submission?',
                        helpFaq17A: 'The application remains unassigned, routing intent is preserved, and admins are notified immediately so coverage gaps can be resolved without losing application context.',
                        helpFaq18Q: 'How do notification preferences work per coordinator?',
                        helpFaq18A: 'Each coordinator can configure which events they receive. Notifications are grouped by type and date, with dedicated overdue views for rapid triage.',
                        helpFaq19Q: 'Can teams export data for audits and executive reviews?',
                        helpFaq19A: 'Yes. Application lists, performance views, and department reports can be exported as CSV or PDF for monthly governance, planning, and compliance reviews.',
                        helpFaq20Q: 'How does the chatbot hand off to application creation?',
                        helpFaq20A: 'If the chatbot cannot resolve within configured turns, it offers a guided application handoff preserving context so interns continue without restarting their description.',
                    },
                    French: {
                        /* Hero */
                        heroHeadline1: 'G\u00e9rez vos stages avec',
                        heroHeadline2: 'confiance gr\u00e2ce \u00e0 InternDesk',
                        heroSubtitle: 'La plateforme pr\u00e9f\u00e9r\u00e9e des organisations qui investissent dans les talents de demain.',
                        heroPlaceholder: 'Entrez votre e-mail',
                        heroTryFree: 'Essayer gratuitement',
                        heroPrivacy: 'En soumettant, j\'accepte la',
                        heroPrivacyLink: 'Politique de confidentialit\u00e9',
                        heroInvalidEmail: 'Veuillez entrer une adresse e-mail valide.',
                        heroThankYou: 'Merci ! V\u00e9rifiez votre e-mail.',
                        heroDashboard: 'Aller au tableau de bord',

                        /* Discover */
                        discoverBadge1: 'Les utilisateurs nous adorent',
                        discoverBadge2: 'Utilisateurs les plus heureux 2023',
                        discoverTitle: 'D\u00e9couvrez InternDesk',
                        discoverTab_ticketList: 'Liste des candidatures',
                        discoverTab_ticketView: 'Vue de la candidature',
                        discoverTab_automations: 'Automatisations',
                        discoverTab_reports: 'Rapports',
                        discoverCta: 'Inscription gratuite',

                        /* Support Heroes */
                        heroesTitle1: 'Nous sommes l\u00e0 pour vous',
                        heroesTitle2: '24h/24, 7j/7, 365j/an',
                        heroesDescription: 'Quand vous avez besoin d\u2019aide, comptez sur nos H\u00e9ros InternDesk. Ils sont forts, rapides et vous aideront \u00e0 tout moment\u00a0!',
                        heroesCta: 'Discutez avec nous',
                        homeSupportHeroesBadge: 'H\u00e9ros InternDesk',
                        homeSlaCardTitle: 'Suivi des d\u00e9lais',
                        homeSlaCardBody: 'Comptes \u00e0 rebours en direct sur chaque candidature. Avertissements ambre, alertes rouges en cas de retard.',
                        homeKnowledgeCardTitle: 'Centre de ressources',
                        homeKnowledgeCardBody: 'Un centre de ressources public complet sur votre sous-domaine \u2014 guides, politiques et recherche.',
                        homeGetStartedHeading: 'Commencer',
                        homeGetStartedLine1: 'Prenez en main la plateforme en moins d\'une heure.',
                        homeGetStartedLine2Prefix: 'Devenez un',
                        homeGetStartedLine2Emphasis: 'utilisateur expert',
                        homeGetStartedLine2Suffix: 'en moins d\'une journ\u00e9e.',
                        homeGetStartedPrimaryCta: 'Commencer',
                        homeGetStartedSecondaryCta: 'R\u00e9server une d\u00e9mo',
                        homeSfsTitle: 'Et toutes les fonctionnalit\u00e9s que les \u00e9quipes stages adorent',
                        homeSfsAutomationTitle: 'Moteur d\'automatisation',
                        homeSfsAutomationBody: 'D\u00e9finissez les conditions une fois \u2014 les candidatures sont rout\u00e9es, escalad\u00e9es et notifi\u00e9es automatiquement.',
                        homeSfsTagsTitle: 'Tags et libell\u00e9s',
                        homeSfsTagsBody: 'Organisez chaque candidature avec des tags color\u00e9s pour que rien ne passe entre les mailles du filet.',
                        homeSfsInboxesTitle: 'D\u00e9partements multiples',
                        homeSfsInboxesBody: 'Donnez \u00e0 chaque d\u00e9partement ou programme son espace d\u00e9di\u00e9 \u00e0 la gestion des stages.',
                        homeSfsAiTitle: 'Copilote IA',
                        homeSfsAiBody: 'L\'IA lit la candidature, sugg\u00e8re une r\u00e9ponse selon votre ton, et r\u00e9sume tout l\'historique.',
                        homeSfsReportsTitle: 'Analytique et rapports',
                        homeSfsReportsBody: 'Suivez la performance \u00e9quipe, les taux de placement et la satisfaction des stagiaires en un coup d\'oeil.',
                        homeSfsRoutingTitle: 'Matching intelligent',
                        homeSfsRoutingBody: 'Chaque candidature trouve instantan\u00e9ment le meilleur superviseur disponible selon le d\u00e9partement et la charge.',
                        homeSfsPreviewAutomationRule: 'R\u00e8gle d\'automatisation',
                        homeSfsPreviewActive: 'Actif',
                        homeSfsPreviewWhen: 'QUAND',
                        homeSfsPreviewThen: 'ALORS',
                        homeSfsPreviewAssignTo: 'Assigner \u00e0',
                        homeSfsPreviewBillingTeam: 'D\u00e9pt. Ing\u00e9nierie',
                        homeSfsPreviewRanTimes: 'Ex\u00e9cut\u00e9 248 fois',
                        homeSfsPreviewAiCustomerMsg: 'Ma candidature de stage #4821 n\'a pas encore de r\u00e9ponse. Pouvez-vous aider?',
                        homeSfsPreviewAiSuggestion: 'Suggestion IA',
                        homeSfsPreviewUseReply: 'Utiliser',
                        homeSfsPreviewRegenerate: 'R\u00e9g\u00e9n\u00e9rer',
                        homeSfsPreviewTicketQueue: 'File de candidatures',
                        homeSfsPreviewBreached: 'en retard',
                        homeSfsPreviewPaymentFailed: 'Placement retard\u00e9',
                        homeSfsPreviewSlaBreachedUrgent: 'D\u00e9lai d\u00e9pass\u00e9 \u00b7 Urgent',
                        homeSfsPreviewKbSearch: 'Rechercher dans le centre de ressources...',
                        homeSfsPreviewKbArticle1: 'Comment soumettre votre rapport de stage',
                        homeSfsPreviewKbMeta1: 'Rapports \u00b7 2 min de lecture',
                        homeSfsPreviewKbArticle2: 'R\u00e9initialiser votre mot de passe portail',
                        homeSfsPreviewKbMeta2: 'Compte \u00b7 1 min de lecture',
                        homeSfsPreviewKbArticle3: 'Suivre le statut de votre placement',
                        homeSfsPreviewKbMeta3: 'Placements \u00b7 3 min de lecture',
                        homeSfsPreviewKbBadge: '24 articles \u00b7 Disponible sur /resources',
                        homeSfsPreviewReportsHead: 'Performance d\'\u00e9quipe \u00b7 Cette semaine',
                        homeBeaconAiAssistant: 'Assistant IA',
                        homeBeaconEndChat: 'Terminer le chat',
                        homeBeaconAskQuestion: 'Posez une question...',
                        homeBeaconAgentsOnline: '2 coordinateurs en ligne',
                        homeBeaconPreviousConversations: 'Conversations pr\u00e9c\u00e9dentes',
                        homeBeaconLastUpdatedToday: 'Derni\u00e8re mise \u00e0 jour aujourd\'hui',
                        homeSfsTagResolved: 'Termin\u00e9',
                        homeSfsTagPending: 'En cours',
                        homeSfsTagBug: 'Probl\u00e8me',
                        homeSfsTagGeneral: 'G\u00e9n\u00e9ral',
                        homeSfsTagOnboarding: 'Onboarding',
                        homeSfsPreviewFriendly: 'Amical',
                        homeSfsPreviewFormal: 'Formel',
                        homeSfsPreviewCantLogin: 'Impossible d\'acc\u00e9der au portail',
                        homeSfsPreviewMinutesLeftHigh: '18 min restantes \u00b7 \u00c9lev\u00e9',
                        homeSfsPreviewAvgReply: 'R\u00e9ponse moy.',
                        homeSfsPreviewResolved: 'Termin\u00e9',
                        homeSfsPreviewUrgent: 'Urgent',
                        homeSfsPreviewAccount2fa: 'Impossible d\'acc\u00e9der au portail stagiaire apr\u00e8s 2FA',
                        homeSfsPreviewCategoryAccount: 'D\u00e9partement : Ing\u00e9nierie',
                        homeSfsPreviewAssignedSara: 'Assign\u00e9 \u00e0 Sara K.',
                        homeSfsPreviewAccountTeamTickets: '\u00c9quipe Ing\u00e9nierie \u00b7 2 candidatures ouvertes',
                        homeSfsPreviewRoutedIn: 'Rout\u00e9 en',
                        homeBeacon3Billing: 'Placement',
                        homeBeacon3SlaBreachSoon: 'D\u00e9lai dans 18 min - r\u00e9pondez maintenant',
                        homeBeacon3CustomerSarah: 'Stagiaire \u00b7 Sarah M.',
                        homeBeacon3CustomerMessage: 'Bonjour, mon placement de stage n\'a pas encore \u00e9t\u00e9 confirm\u00e9 et la date de d\u00e9but est la semaine prochaine.',
                        homeBeacon3AgentReply: 'Bonjour Sarah, j\'ai confirm\u00e9 votre placement au d\u00e9partement Ing\u00e9nierie. Votre superviseur vous contactera avec les d\u00e9tails d\'int\u00e9gration sous peu.',
                        homeBeacon3Tone: 'Ton :',
                        homeBeacon3Professional: 'Professionnel',
                        homeBeacon3OpenBreached: 'ouverts \u00b7 2 en retard',
                        homeBeacon3FilterAll: 'Tous',
                        homeBeacon3FilterUnassigned: 'Non assign\u00e9s',
                        homeBeacon3NoAccountNeeded: 'Aucun compte requis \u2014 juste votre e-mail',
                        homeBeacon3StepSubmitted: 'Candidature soumise',
                        homeBeacon3StepAssigned: 'Assign\u00e9 \u00e0 un coordinateur',
                        homeBeacon3StepInProgress: 'En cours',
                        homeBeacon3ReplyToAgent: 'R\u00e9pondre au coordinateur',

                        /* Beacons */
                        beacon1Title: 'D\u00e9couvrez InternDesk AI : votre hub de gestion de stages',
                        beacon1Tab1Title: 'R\u00e9pondez instantan\u00e9ment avec l\'IA',
                        beacon1Tab1Body: 'Laissez l\'IA traiter les questions courantes des stagiaires 24h/24 \u2014 sans attente, sans coordinateur.',
                        beacon1Tab2Title: 'Gardez l\'accompagnement humain \u00e0 port\u00e9e de main',
                        beacon1Tab2Body: 'Que vous proposiez chat en direct, e-mail, ou les deux, vos coordinateurs restent \u00e0 deux clics.',
                        beacon1Tab3Title: 'Faites gagner du temps aux stagiaires',
                        beacon1Tab3Body: 'Permettez l\'acc\u00e8s facile aux conversations pr\u00e9c\u00e9dentes pour reprendre l\u00e0 o\u00f9 ils s\'\u00e9taient arr\u00eat\u00e9s.',
                        beacon1DemoMsg1: 'Bonjour! Je peux r\u00e9pondre instantan\u00e9ment \u00e0 vos questions. De quoi avez-vous besoin?',
                        beacon1DemoMsg2: 'Quel est le processus d\'int\u00e9gration de stage?',
                        beacon1DemoMsg3: 'Une fois votre placement confirm\u00e9, vous recevrez un kit d\'int\u00e9gration avec les coordonn\u00e9es de votre superviseur et votre planning sous 48h ! \ud83c\udf93',
                        beacon1DemoHuman1: 'Salut Amber! Nikita \u00e0 l\'appareil. Comment puis-je vous aider aujourd\'hui?',
                        beacon1DemoHuman2: 'Bonjour! Je voulais conna\u00eetre le statut de ma candidature de stage.',
                        beacon1DemoHuman3: 'Le num\u00e9ro de candidature est #10283089',
                        beacon2Title: 'Restez organis\u00e9 automatiquement',
                        beacon2Tab1Title: 'Trouvez le bon superviseur',
                        beacon2Tab1Body: 'Routez automatiquement chaque candidature vers le superviseur le plus adapt\u00e9 pour encadrer le stagiaire.',
                        beacon2Tab2Title: 'Ne manquez jamais les d\u00e9lais importants',
                        beacon2Tab2Body: 'Gardez les questions de stage urgentes visibles avec des priorit\u00e9s claires et des alertes intelligentes.',
                        beacon2Tab3Title: 'Simplifiez la file pour votre \u00e9quipe',
                        beacon2Tab3Body: 'Aidez tout le monde \u00e0 \u00eatre plus efficace avec des vues personnalis\u00e9es qui regroupent les candidatures par d\u00e9partement.',
                        beacon3TitlePrefix: 'Tout ce dont votre \u00e9quipe stages a besoin',
                        beacon3TitleEmphasis: 'au m\u00eame endroit',
                        beacon3Tab1Title: 'Copilote IA pour chaque coordinateur',
                        beacon3Tab1Body: 'L\'IA lit toute la candidature, g\u00e9n\u00e8re une r\u00e9ponse sugg\u00e9r\u00e9e selon le ton choisi et r\u00e9sume l\'historique complet pour que les coordinateurs avancent plus vite.',
                        beacon3Tab2Title: 'Matching intelligent, suivi des d\u00e9lais en direct',
                        beacon3Tab2Body: 'Chaque candidature est auto-assign\u00e9e au meilleur coordinateur disponible, pendant que les comptes \u00e0 rebours et alertes de retard gardent les temps de r\u00e9ponse sous contr\u00f4le.',
                        beacon3Tab3Title: 'Z\u00e9ro friction pour les stagiaires',
                        beacon3Tab3Body: 'Aucun compte requis. Les stagiaires v\u00e9rifient par e-mail, re\u00e7oivent un lien de suivi et peuvent suivre ou r\u00e9pondre depuis n\'importe quel appareil.',

                        /* Navbar */
                        products: 'Produits',
                        solutions: 'Solutions',
                        resources: 'Ressources',
                        pricing: 'Tarifs',
                        companyMenu: 'Entreprise',
                        tryFree: 'Inscription gratuite',
                        viewDemo: 'Connexion',
                        dashboard: 'Tableau de bord',
                        platform: 'Plateforme',
                        platformOverview: 'Aper\u00e7u de la plateforme',
                        integrations: 'Int\u00e9grations',
                        latestInnovations: 'Derni\u00e8res innovations',
                        appMarketplace: 'Marketplace d\'apps',
                        developers: 'D\u00e9veloppeurs',
                        trending: 'Tendances',
                        trendItem1: 'Sommet InternDesk 2026',
                        trendDesc1: 'Un \u00e9v\u00e9nement mondial pour les leaders RH, stages et talents.',
                        trendItem2: 'Co\u00fbts cach\u00e9s du suivi manuel',
                        trendDesc2: 'D\u00e9couvrez la taxe de complexit\u00e9 qui co\u00fbte cher \u00e0 votre programme de stages.',
                        trendItem3: 'InternDesk s\'associe aux meilleures universit\u00e9s',
                        trendDesc3: 'D\u00e9couvrez comment InternDesk alimente des partenariats stages mondiaux.',
                        navProductFeatureTitle: 'D\u00e9couvrez InternDesk IA',
                        navProductFeatureBadge: 'NOUVEAU',
                        navProductFeatureDescription: 'Une IA agentique qui raisonne, agit et r\u00e9sout',
                        navProductFeatureCta: 'Explorer InternDesk IA',
                        productCard1Title: 'Gestionnaire de placements',
                        productCard1Desc: 'Placement et suivi de stages modernes.',
                        productCard2Title: 'InternDesk Omni',
                        productCard2Desc: 'Communication stagiaire omnicanale propuls\u00e9e par l\'IA.',
                        productCard3Title: 'InternDesk Lite',
                        productCard3Desc: 'Gestion de stages simple pour \u00e9quipes en croissance.',
                        productLearnMore: 'En savoir plus',
                        productFeatured: '\u00c0 la une',
                        productTour: 'Tour du produit',
                        productTourDesc1: 'Voyez comment les \u00e9quipes g\u00e8rent les placements plus vite.',
                        productTourDesc2: 'Explorez l\'automatisation pour chaque workflow de stage.',
                        productTourDesc3: 'D\u00e9couvrez un processus de candidature plus rapide en minutes.',
                        productWhatsNew: 'Nouveaut\u00e9s',
                        productUpdateDesc: 'Derni\u00e8res am\u00e9liorations IA et int\u00e9grations.',
                        productAllTrials: 'Voir tous les essais produits',
                        companyAbout: '\u00c0 propos',
                        companyAboutDesc: 'D\u00e9couvrez notre mission, histoire et valeurs.',
                        companyCareers: 'Carri\u00e8res',
                        companyCareersDesc: 'Cr\u00e9ez des produits qui aident les \u00e9quipes \u00e0 mieux g\u00e9rer les talents.',
                        companyHelpCenterDesc: 'Parcourez nos guides, FAQ et ressources de la plateforme.',
                        companyContactDesc: 'Contactez notre \u00e9quipe pour vos questions commerciales ou plateforme.',
                        companyPartnerDesc: 'D\u00e9veloppez-vous avec notre r\u00e9seau mondial.',
                        navResourceFeatureTitle: 'Apprenez avec des ressources concr\u00e8tes',
                        navResourceFeatureDescription: 'Playbooks, documentation et guides pour lancer de meilleurs workflows de stages.',
                        navResourceFeatureCta: 'Explorer les ressources',
                        byTeam: 'Par \u00e9quipe',
                        customerService: 'Op\u00e9rations RH',
                        itSupport: 'Support IT',
                        hrTeams: '\u00c9quipes RH',
                        salesTeams: 'Acquisition de talents',
                        bySize: 'Par taille d\'entreprise',
                        enterprise: 'Entreprise',
                        midMarket: 'March\u00e9 interm\u00e9diaire',
                        smallBusiness: 'Petite entreprise',
                        startups: 'Startups',
                        learn: 'Apprendre',
                        blog: 'Blog',
                        documentation: 'Documentation',
                        webinars: 'Webinaires',
                        academy: 'Acad\u00e9mie',
                        connect: 'Connecter',
                        community: 'Communaut\u00e9',
                        events: '\u00c9v\u00e9nements',
                        partnerProgram: 'Programme partenaire',
                        support: 'Assistance',

                        /* Utility Bar */
                        utilitySignIn: 'Se connecter',
                        utilityLogout: 'Se d\u00e9connecter',
                        utilityHelpCenter: 'Centre d\'aide',
                        utilityCompany: 'Entreprise',
                        utilityContactUs: 'Nous contacter',

                        /* Footer */
                        footerTagline: 'Gestion de stages moderne pour \u00e9quipes modernes.',
                        footerProducts: 'Produits',
                        footerPlatformOverview: 'Aper\u00e7u de la plateforme',
                        footerIntegrations: 'Int\u00e9grations',
                        footerMarketplace: 'Marketplace d\'apps',
                        footerDevelopers: 'D\u00e9veloppeurs',
                        footerSolutions: 'Solutions',
                        footerCustomerService: 'Op\u00e9rations RH',
                        footerItSupport: 'Support IT',
                        footerHrTeams: '\u00c9quipes RH',
                        footerSalesTeams: 'Acquisition de talents',
                        footerResources: 'Ressources',
                        footerBlog: 'Blog',
                        footerDocumentation: 'Documentation',
                        footerWebinars: 'Webinaires',
                        footerCommunity: 'Communaut\u00e9',
                        footerCompany: 'Entreprise',
                        footerAbout: '\u00c0 propos',
                        footerCareers: 'Carri\u00e8res',
                        footerContact: 'Contact',
                        footerPrivacy: 'Politique de confidentialit\u00e9',
                        footerRights: 'Tous droits r\u00e9serv\u00e9s.',
                        footerColProduct: 'Produit',
                        footerLinkDashboard: 'Tableau de bord',
                        footerLinkFeatures: 'Fonctionnalit\u00e9s',
                        footerLinkDiscover: 'D\u00e9couvrir',
                        footerLinkFooter: 'Pied de page',
                        footerColResources: 'Ressources',
                        footerLinkGettingStarted: 'D\u00e9marrage',
                        footerLinkAutomationIdeas: 'Id\u00e9es de workflows',
                        footerLinkCustomerStories: 'T\u00e9moignages de r\u00e9ussite',
                        footerLinkBrandAssets: 'Ressources de marque',
                        footerColQuickLinks: 'Liens rapides',
                        footerLinkHome: 'Accueil',
                        footerLinkProductTour: 'Tour du produit',
                        footerLinkTestimonials: 'T\u00e9moignages',
                        footerLinkFooterLayout: 'Mise en page du footer',
                        footerColCompanySupport: 'Entreprise et support',
                        footerLinkAbout: '\u00c0 propos',
                        footerLinkHelpCenter: 'Centre d\'aide',
                        footerLinkContact: 'Contact',
                        footerLinkStatus: 'Statut',
                        footerBrand: 'InternDesk',

                        /* Notification banner */
                        notificationBannerLine: 'Nous serions ravis de vous aider. Parlez \u00e0 notre',
                        notificationBannerStrong: '\u00e9quipe InternDesk.',
                        notificationBannerCta: 'Discuter maintenant ->',
                        notificationBannerDismiss: 'Fermer la notification',

                        /* Chatbot widget */
                        chatbotWelcome1: 'Bienvenue sur InternDesk ! Nous sommes l\u00e0 pour vous aider avec toutes vos questions sur votre stage. Comment pouvons-nous vous aider aujourd\'hui?',
                        chatbotWelcome2: 'Bonjour ! Besoin d\'un coup de main pour votre stage ? Nous sommes pr\u00eats \u00e0 vous aider tout de suite.',
                        chatbotWelcome3: 'Bon retour ! Nous vous attendions. Que peut faire notre \u00e9quipe stages pour vous aujourd\'hui?',
                        chatbotWelcome4: 'Salut ! Merci de nous avoir contact\u00e9s. Dites-nous comment nous pouvons vous aider dans votre parcours de stage.',
                        chatbotWelcome5: 'Bonjour ! Nous sommes l\u00e0 pour vous offrir un accompagnement rapide et convivial. Que puis-je faire pour vous?',
                        chatbotNoConversationsTitle: 'Aucune conversation pour le moment',
                        chatbotNoConversationsBody: 'Touchez ci-dessous pour d\u00e9marrer une conversation.<br>Nous vous aiderons tout de suite!',
                        chatbotStartedPrefix: 'Commenc\u00e9e',
                        chatbotEnded: 'Termin\u00e9e',
                        chatbotRemoveConversation: 'Supprimer la conversation',
                        chatbotNewConversation: 'Nouvelle conversation',
                        chatbotBuiltWith: 'PROPULS\u00c9 PAR INTERNDESK AI',
                        chatbotRepliesFast: 'R\u00e9pond g\u00e9n\u00e9ralement instantan\u00e9ment',
                        chatbotQuickActions: 'Actions rapides',
                        chatbotQuickReply1: 'Comment fonctionne la candidature de stage?',
                        chatbotQuickReply2: 'Puis-je l\'essayer gratuitement?',
                        chatbotQuickReply3: 'Quelles int\u00e9grations prenez-vous en charge?',
                        chatbotQuickReply4: 'Parlez-moi des tarifs',
                        chatbotInputPlaceholder: 'Tapez votre message...',

                        /* About page */
                        aboutTypewriter: '\u00c0 propos',
                        aboutHeroTitle: 'Construire un logiciel de stages qui reste humain \u00e0 grande \u00e9chelle',
                        aboutHeroDescription: 'InternDesk a \u00e9t\u00e9 cr\u00e9\u00e9 pour supprimer le chaos de la gestion des stages. Nous avons construit une plateforme unique o\u00f9 les \u00e9quipes peuvent router les candidatures intelligemment, r\u00e9pondre plus vite gr\u00e2ce \u00e0 l\'IA et g\u00e9rer chaque placement avec confiance.',
                        aboutHeroCtaPrimary: 'Parler \u00e0 notre \u00e9quipe',
                        aboutHeroCtaSecondary: 'Explorer le centre d\'aide',
                        aboutPillar1Title: 'Port\u00e9e mondiale',
                        aboutPillar1Body: 'Des \u00e9quipes de tous les fuseaux horaires font confiance \u00e0 InternDesk pour garder leurs op\u00e9rations de stages actives.',
                        aboutPillar2Title: 'Con\u00e7u pour l\'\u00e9chelle',
                        aboutPillar2Body: 'Une architecture de niveau entreprise pens\u00e9e d\u00e8s le premier jour pour la croissance.',
                        aboutPillar3Title: 'Confidentialit\u00e9 d\'abord',
                        aboutPillar3Body: 'Vos donn\u00e9es restent les v\u00f4tres avec une isolation stricte et une transparence totale.',
                        aboutPillar4Title: 'Centr\u00e9 sur l\'humain',
                        aboutPillar4Body: 'Une IA qui renforce les coordinateurs sans jamais remplacer le lien humain.',
                        aboutStoryTitle: 'Notre histoire',
                        aboutStoryBody1: 'Nous sommes partis d\'un constat : les \u00e9quipes RH g\u00e9raient des programmes de stages \u00e0 travers des bo\u00eetes mail, des feuilles de calcul et des workflows fragiles. Les candidatures \u00e9taient retard\u00e9es, la responsabilit\u00e9 \u00e9tait floue et les managers manquaient de visibilit\u00e9 fiable. Nous avons repens\u00e9 la gestion des stages comme un syst\u00e8me d\'exploitation unique.',
                        aboutStoryBody2: 'Aujourd\'hui, les organisations d\u00e9ploient InternDesk en quelques heures, pas en plusieurs mois. Les admins d\u00e9finissent d\u00e9partements, d\u00e9lais, r\u00e8gles d\'automatisation et groupes d\'\u00e9quipe. Les coordinateurs re\u00e7oivent des suggestions IA contextuelles et des r\u00e9sum\u00e9s instantan\u00e9s. Les stagiaires re\u00e7oivent des mises \u00e0 jour sans friction de compte. Chaque action est tra\u00e7able, mesurable et pens\u00e9e pour l\'\u00e9chelle.',
                        aboutDifferenceTitle: 'Ce qui rend InternDesk diff\u00e9rent',
                        aboutDifference1Title: 'Isolation multi-tenant',
                        aboutDifference1Body: 'Chaque organisation dispose de son propre sous-domaine, de sa port\u00e9e de donn\u00e9es et d\'un mod\u00e8le de configuration avec une s\u00e9paration stricte.',
                        aboutDifference2Title: 'Exp\u00e9rience stagiaire sans connexion',
                        aboutDifference2Body: 'Les stagiaires se v\u00e9rifient par e-mail puis continuent via un lien de suivi, ce qui r\u00e9duit l\'abandon et la friction.',
                        aboutDifference3Title: 'Moteur de matching intelligent',
                        aboutDifference3Body: 'Les candidatures sont rout\u00e9es par d\u00e9partement, programme, sp\u00e9cialit\u00e9s, charge et disponibilit\u00e9 en quasi temps r\u00e9el.',
                        aboutDifference4Title: 'IA copilote, pas remplacement',
                        aboutDifference4Body: 'Les coordinateurs gardent le contr\u00f4le pendant que l\'IA g\u00e8re les r\u00e9sum\u00e9s, suggestions et brouillons r\u00e9p\u00e9titifs.',
                        aboutGrowthTitle: 'Comment les \u00e9quipes grandissent avec nous',
                        aboutGrowthPhase1Label: 'Phase 1',
                        aboutGrowthPhase1Title: 'Lancer en quelques jours',
                        aboutGrowthPhase1Body: 'Les admins pilotent l\'onboarding, configurent les d\u00e9partements et la politique de d\u00e9lais, puis int\u00e8grent le portail de candidature avec un seul script.',
                        aboutGrowthPhase2Label: 'Phase 2',
                        aboutGrowthPhase2Title: 'Automatiser les op\u00e9rations',
                        aboutGrowthPhase2Body: 'Les r\u00e8gles assignent les candidatures, d\u00e9clenchent des alertes et escaladent automatiquement les risques de d\u00e9lai pendant que les managers suivent les tableaux de bord en direct.',
                        aboutGrowthPhase3Label: 'Phase 3',
                        aboutGrowthPhase3Title: 'Optimiser la performance',
                        aboutGrowthPhase3Body: 'Les \u00e9quipes affinent les workflows avec l\'analytique, la sant\u00e9 des d\u00e9partements et des classements coordinateurs qui r\u00e9v\u00e8lent rapidement les goulots d\'\u00e9tranglement.',
                        aboutNoteTitle: 'Un mot de notre \u00e9quipe',
                        aboutNoteBody1: 'Nous concevons InternDesk pour qu\'il soit clair, rapide et fiable d\u00e8s le premier jour. Nous soignons les d\u00e9tails op\u00e9rationnels : qualit\u00e9 des handoffs, coh\u00e9rence des r\u00e9ponses, visibilit\u00e9 des escalades et maintenabilit\u00e9 long terme. Votre \u00e9quipe stages ne doit jamais \u00eatre frein\u00e9e par l\'outil ; elle doit \u00eatre amplifi\u00e9e.',
                        aboutNoteBody2: 'Que vous lanciez votre premier programme de stages ou que vous montiez en \u00e9chelle sur plusieurs r\u00e9gions, nos \u00e9quipes produit et succ\u00e8s client vous aident \u00e0 construire des workflows durables.',
                        aboutVisionTitle: 'Vision produit approfondie',
                        aboutVisionBody1: 'Nous pensons qu\'une plateforme de stages ne doit pas seulement suivre des candidatures, mais coordonner des r\u00e9sultats. Chaque interaction doit apporter du contexte structur\u00e9, une responsabilit\u00e9 claire, des d\u00e9lais actionnables et des signaux de qualit\u00e9 mesurables. Dans InternDesk, chaque candidature est li\u00e9e \u00e0 des d\u00e9partements, priorit\u00e9s, horloges de d\u00e9lai et logique de matching op\u00e9rationnelle.',
                        aboutVisionBody2: 'Quand le volume de candidatures augmente, la complexit\u00e9 augmente plus vite que les effectifs. Nous avons con\u00e7u InternDesk pour absorber cette complexit\u00e9 avec des valeurs par d\u00e9faut intelligentes et une automatisation configurable. R\u00e8gles d\'assignation, escalades, alertes de d\u00e9lai et actions de cycle de vie travaillent ensemble pour r\u00e9duire l\'orchestration manuelle.',
                        aboutVisionBody3: 'Nous accordons aussi une grande importance \u00e0 la qualit\u00e9 d\'exp\u00e9rience pour chaque r\u00f4le. Les admins ont besoin de contr\u00f4le et de visibilit\u00e9. Les coordinateurs ont besoin de vitesse et de contexte. Les stagiaires ont besoin d\'un parcours fluide. C\'est pourquoi nous avons unifi\u00e9 suivi sans connexion, r\u00e9sum\u00e9s IA, notes de collaboration et outils de ressources dans un seul workflow.',
                        aboutInfrastructureTitle: 'Comment nous concevons l\'infrastructure de stages',
                        aboutInfrastructure1Title: 'Fiabilit\u00e9 d\'abord',
                        aboutInfrastructure1Body: 'Les workflows sont con\u00e7us pour une ex\u00e9cution pr\u00e9visible. Assignation, escalade, notification et cl\u00f4ture suivent une s\u00e9quence d\u00e9terministe pour maintenir la confiance lors des pics de volume.',
                        aboutInfrastructure2Title: 'Efficacit\u00e9 coordinateur',
                        aboutInfrastructure2Body: 'Les coordinateurs acc\u00e8dent instantan\u00e9ment au contexte via les r\u00e9sum\u00e9s IA, des \u00e9tats de candidature clairs et des r\u00e9f\u00e9rences au centre de ressources. Cela r\u00e9duit le temps de r\u00e9ponse et les allers-retours inutiles.',
                        aboutInfrastructure3Title: 'R\u00e9sultats visibles',
                        aboutInfrastructure3Body: 'Le management obtient une visibilit\u00e9 op\u00e9rationnelle compl\u00e8te via rapports, sant\u00e9 des d\u00e9lais, tendances par d\u00e9partement et jeux de donn\u00e9es exportables pour le pilotage quotidien et trimestriel.',
                        aboutCultureTitle: 'Au coeur de notre culture stages mondiale',
                        aboutCultureBody: 'Nous op\u00e9rons comme une seule \u00e9quipe distribu\u00e9e, avec des standards partag\u00e9s et une flexibilit\u00e9 locale d\'ex\u00e9cution. Produit, succ\u00e8s et ing\u00e9nierie collaborent en continu sur les playbooks de coordination, les templates de workflow et l\'architecture de ressources afin d\'assurer des r\u00e9sultats coh\u00e9rents.',
                        aboutCommitmentTitle: 'Notre engagement',
                        aboutCommitmentBody1: 'Nous nous engageons \u00e0 construire un logiciel de stages rapide, observable et adaptable \u00e0 mesure que votre organisation grandit. Nous livrons des fonctionnalit\u00e9s qui r\u00e9duisent la friction op\u00e9rationnelle, au lieu d\'ajouter de la complexit\u00e9 d\'interface.',
                        aboutCommitmentBody2: 'Nous nous engageons \u00e0 la transparence sur le fonctionnement de l\'automatisation et la g\u00e9n\u00e9ration des suggestions IA. Les \u00e9quipes doivent comprendre et contr\u00f4ler le syst\u00e8me, pas deviner son comportement.',
                        aboutCommitmentBody3: 'Nous nous engageons \u00e0 \u00eatre un partenaire durable. Notre \u00e9quipe accompagne la strat\u00e9gie d\'impl\u00e9mentation, la migration et l\'optimisation continue pour faire progresser votre programme de stages dans le temps.',

                        /* Contact page */
                        contactTypewriter: 'Contact',
                        contactHeroTitle: 'Lancez de meilleurs programmes de stages, plus vite, avec nous',
                        contactHeroDescription: 'Dites-nous ce dont vous avez besoin et notre \u00e9quipe vous guide sur la mise en place, la migration, la strat\u00e9gie d\'automatisation et l\'int\u00e9gration du portail.',
                        contactFormTitle: 'Envoyer un message',
                        contactFormRequiredNote: 'Les champs marqu\u00e9s d\'un * sont obligatoires.',
                        contactSuccessMessage: 'Message envoy\u00e9 avec succ\u00e8s. Nous vous r\u00e9pondrons rapidement.',
                        contactFieldName: 'Nom complet *',
                        contactFieldNamePlaceholder: 'Jane Doe',
                        contactFieldEmail: 'E-mail professionnel *',
                        contactFieldEmailPlaceholder: 'jane@company.com',
                        contactFieldCompany: 'Nom de l\'organisation *',
                        contactFieldCompanyPlaceholder: 'Acme Inc',
                        contactFieldTeamSize: 'Taille de l\'\u00e9quipe',
                        contactTeamSizeOption0: 'S\u00e9lectionnez une option',
                        contactTeamSizeOption1: '1-5 coordinateurs',
                        contactTeamSizeOption2: '6-20 coordinateurs',
                        contactTeamSizeOption3: '21-50 coordinateurs',
                        contactTeamSizeOption4: '50+ coordinateurs',
                        contactFieldTopic: 'Sujet *',
                        contactTopicOption0: 'Choisissez un sujet',
                        contactTopicOption1: 'R\u00e9server une d\u00e9mo produit',
                        contactTopicOption2: 'Migration et onboarding',
                        contactTopicOption3: 'Tarifs et offres',
                        contactTopicOption4: 'Support technique',
                        contactFieldMessage: 'Message *',
                        contactFieldMessagePlaceholder: 'Parlez-nous de vos objectifs de stages, du volume de candidatures et de votre workflow actuel.',
                        contactResponseNote: 'Nous r\u00e9pondons sous un jour ouvr\u00e9.',
                        contactSubmit: 'Envoyer le message',
                        contactSalesTitle: 'Parler aux ventes',
                        contactSalesBody: 'Pour les tarifs et la planification d\'impl\u00e9mentation.',
                        contactSupportTitle: 'Support plateforme',
                        contactSupportBody: 'Les utilisateurs existants peuvent obtenir une aide rapide de notre \u00e9quipe support.',
                        contactChecklistTitle: 'Checklist de d\u00e9marrage rapide',
                        contactChecklist1: '1. Partagez votre volume actuel de stagiaires et vos d\u00e9partements.',
                        contactChecklist2: '2. Nous cartographions d\u00e9partements, d\u00e9lais et r\u00e8gles d\'automatisation.',
                        contactChecklist3: '3. Votre portail passe en production avec une seule balise script.',
                        contactOfficesTitle: 'Nos bureaux dans le monde',
                        contactWhyTitle: 'Pourquoi les \u00e9quipes nous contactent avant le lancement',
                        contactWhyBody1: 'La plupart des \u00e9quipes nous contactent lorsqu\'elles remplacent des workflows de stages fragment\u00e9s et ont besoin d\'un plan de d\u00e9ploiement fiable. Nous aidons \u00e0 d\u00e9finir les matrices de priorit\u00e9, la propri\u00e9t\u00e9 des files et les limites d\'escalade avant la premi\u00e8re candidature en production.',
                        contactWhyBody2: 'Nous cartographions aussi le parcours stagiaire de bout en bout : points de candidature, mod\u00e8les de r\u00e9ponse, auto-r\u00e9ponses, seuils de d\u00e9lai et politique de compl\u00e9tion. Le r\u00e9sultat : une op\u00e9ration de stages coh\u00e9rente sur tous les d\u00e9partements.',
                        contactAfterTitle: 'Ce qui se passe apr\u00e8s votre prise de contact',
                        contactAfter1Title: 'Appel de d\u00e9couverte',
                        contactAfter1Body: 'Nous passons en revue vos d\u00e9partements, volume attendu, structure d\'\u00e9quipe et objectifs de r\u00e9ponse pour concevoir un d\u00e9ploiement pragmatique.',
                        contactAfter2Title: 'Plan de configuration',
                        contactAfter2Body: 'D\u00e9partements, d\u00e9lais, r\u00e8gles d\'automatisation et branding du portail sont pr\u00e9par\u00e9s selon votre workflow.',
                        contactAfter3Title: 'Support de mise en production',
                        contactAfter3Body: 'Nous restons avec votre \u00e9quipe pendant le lancement, surveillons les premi\u00e8res candidatures et ajustons le matching ou les flux de r\u00e9ponse si n\u00e9cessaire.',

                        /* Help center page */
                        helpTypewriter: 'Centre d\'aide',
                        helpHeroTitle: 'Des r\u00e9ponses pour les admins, les coordinateurs et les stagiaires au m\u00eame endroit',
                        helpHeroDescription: 'D\u00e9couvrez comment InternDesk g\u00e8re le routage des candidatures, le copilote IA, l\'automatisation des d\u00e9lais, les portails int\u00e9grables et les workflows de reporting.',
                        helpSearchLabel: 'Rechercher des r\u00e9ponses',
                        helpSearchPlaceholder: 'Exemple : d\u00e9lais, automatisation, chatbot, routage des candidatures',
                        helpPopularAnswersTitle: 'R\u00e9ponses populaires',
                        helpShowMoreAnswers: 'Afficher 10 r\u00e9ponses suppl\u00e9mentaires',
                        helpJourneyTitle: 'Parcours de la candidature',
                        helpJourney1: '1. Le stagiaire soumet une candidature via le portail.',
                        helpJourney2: '2. L\'automatisation route vers le d\u00e9partement + le meilleur coordinateur.',
                        helpJourney3: '3. Le coordinateur re\u00e7oit un r\u00e9sum\u00e9 IA et une suggestion.',
                        helpJourney4: '4. Placement confirm\u00e9, l\'int\u00e9gration commence.',
                        helpRoleWorkflowsTitle: 'Workflows par r\u00f4le',
                        helpRoleAdmin: 'Admin : configure d\u00e9partements, d\u00e9lais, groupes et r\u00e8gles.',
                        helpRoleAgent: 'Coordinateur : g\u00e8re la file, les notes, les r\u00e9ponses et les liens ressources.',
                        helpRoleCustomer: 'Stagiaire : v\u00e9rifie son e-mail et suit sans connexion.',
                        helpAssistanceTitle: 'Besoin d\'aide directe?',
                        helpAssistanceBody: 'Pour la mise en place de compte, la migration et les workflows personnalis\u00e9s, contactez notre \u00e9quipe.',
                        helpAssistancePrimaryCta: 'Contacter l\'\u00e9quipe',
                        helpAssistanceSecondaryCta: 'E-mail support',
                        helpLifecycleTitle: 'Cycle de stages complet dans une seule plateforme',
                        helpLifecycleBody1: 'InternDesk est con\u00e7u pour couvrir tout le parcours, de la candidature \u00e0 la compl\u00e9tion. Les nouvelles candidatures entrent via votre portail de marque, sont cat\u00e9goris\u00e9es et prioris\u00e9es, puis rout\u00e9es vers le bon d\u00e9partement pour action rapide. Les coordinateurs collaborent avec notes priv\u00e9es, suggestions IA et r\u00e9f\u00e9rences de ressources pendant que les stagiaires suivent par e-mail et lien de tracking.',
                        helpLifecycleBody2: 'Cette approche r\u00e9duit la fragmentation op\u00e9rationnelle. Au lieu de changer d\'outil pour le routage, la collaboration, la visibilit\u00e9 des d\u00e9lais et la communication avec les stagiaires, chaque r\u00f4le travaille au m\u00eame endroit avec un \u00e9tat coh\u00e9rent et une source de v\u00e9rit\u00e9 partag\u00e9e.',
                        helpPlaybooksTitle: 'Playbooks op\u00e9rationnels pour chaque r\u00f4le',
                        helpPlaybookAdminTitle: 'Playbook admin',
                        helpPlaybookAdminBody: 'Configurez les d\u00e9partements, paliers de d\u00e9lais, r\u00e8gles d\'assignation et politiques de notification. Surveillez les retards en direct et optimisez le d\u00e9bit de l\'\u00e9quipe via des rapports centralis\u00e9s.',
                        helpPlaybookAgentTitle: 'Playbook coordinateur',
                        helpPlaybookAgentBody: 'Prenez les files tri\u00e9es par priorit\u00e9, consultez le r\u00e9sum\u00e9 IA, composez une r\u00e9ponse avec suggestions optionnelles, joignez des fichiers, ins\u00e9rez des liens ressources et confirmez le placement avec confiance.',
                        helpPlaybookCustomerTitle: 'Playbook stagiaire',
                        helpPlaybookCustomerBody: 'Soumettez une candidature sans inscription, v\u00e9rifiez par e-mail, suivez via le lien de tracking, r\u00e9pondez depuis la bo\u00eete mail et recevez des mises \u00e0 jour claires \u00e0 chaque changement de statut.',
                        helpFaq1Q: 'Comment fonctionne la candidature de stage sans connexion?',
                        helpFaq1A: 'Les stagiaires soumettent une candidature via le portail du site, v\u00e9rifient leur e-mail puis re\u00e7oivent un lien de suivi. Ils peuvent suivre les mises \u00e0 jour et r\u00e9pondre sans cr\u00e9er de compte.',
                        helpFaq2Q: 'Comment les candidatures sont-elles rout\u00e9es vers les bons coordinateurs?',
                        helpFaq2A: 'Le moteur d\'automatisation applique des r\u00e8gles selon le d\u00e9partement, le programme, la priorit\u00e9, le groupe assign\u00e9 et la disponibilit\u00e9, puis choisit le coordinateur le plus adapt\u00e9 selon sp\u00e9cialit\u00e9s et charge.',
                        helpFaq3Q: 'Que fait le copilote IA pour les coordinateurs?',
                        helpFaq3A: 'L\'IA lit toute la candidature, g\u00e9n\u00e8re un r\u00e9sum\u00e9 concis et propose des r\u00e9ponses modifiables dans le ton choisi. Les coordinateurs peuvent r\u00e9g\u00e9n\u00e9rer, affiner ou ignorer instantan\u00e9ment.',
                        helpFaq4Q: 'Comment le suivi des d\u00e9lais \u00e9vite-t-il les dates manqu\u00e9es?',
                        helpFaq4A: 'Chaque candidature re\u00e7oit une \u00e9ch\u00e9ance selon la politique de priorit\u00e9. Des comptes \u00e0 rebours affichent le risque et des notifications de retard sont envoy\u00e9es aux coordinateurs et admins concern\u00e9s.',
                        helpFaq5Q: 'Les administrateurs peuvent-ils configurer l\'automatisation sans code?',
                        helpFaq5A: 'Oui. Les admins cr\u00e9ent des r\u00e8gles condition-action depuis un panneau visuel. Ils peuvent assigner des coordinateurs/groupes, ajuster la priorit\u00e9, d\u00e9clencher des auto-r\u00e9ponses et escalader selon d\u00e9lai ou r\u00e8gles VIP.',
                        helpFaq6Q: 'Quelle automatisation de cycle de vie intervient apr\u00e8s la confirmation de placement?',
                        helpFaq6A: 'Les placements confirm\u00e9s d\u00e9clenchent des notifications stagiaires, des rappels d\'\u00e9valuation et des plannings de rapports de progression. Les stages termin\u00e9s s\'archivent automatiquement avec l\'historique complet.',
                        helpFaq7Q: 'Comment le centre de ressources aide-t-il coordinateurs et stagiaires?',
                        helpFaq7A: 'Les stagiaires peuvent parcourir/rechercher les articles publics sous /resources. Les coordinateurs peuvent rechercher le contenu des ressources directement dans les outils de r\u00e9ponse et ins\u00e9rer des liens sans quitter la conversation.',
                        helpFaq8Q: 'Quels portails peuvent \u00eatre int\u00e9gr\u00e9s sur notre site?',
                        helpFaq8A: 'InternDesk fournit un portail de candidature, un widget chatbot IA et un widget de recherche de ressources. Chacun utilise un code d\'int\u00e9gration par script et se g\u00e8re depuis une zone d\'int\u00e9grations unique.',
                        helpFaq9Q: 'Comment les donn\u00e9es sont-elles isol\u00e9es en mode multi-tenant?',
                        helpFaq9A: 'Chaque organisation fonctionne sur son propre sous-domaine et son propre jeu de donn\u00e9es. Candidatures, stagiaires, param\u00e8tres et analytics restent isol\u00e9s sans acc\u00e8s crois\u00e9.',
                        helpFaq10Q: 'Quels rapports sont disponibles pour l\'analyse de performance?',
                        helpFaq10A: 'Les rapports incluent tendances globales, performance coordinateurs, analyse de candidatures et sant\u00e9 des d\u00e9partements. Les \u00e9quipes peuvent exporter en CSV/PDF et suivre classements et comportements de placement.',
                        helpFaq11Q: 'Les coordinateurs peuvent-ils mettre \u00e0 jour plusieurs candidatures en masse?',
                        helpFaq11A: 'Oui. Coordinateurs et admins peuvent assigner en masse, changer le statut, ajuster la priorit\u00e9 et effectuer des actions batch depuis des vues filtr\u00e9es pour acc\u00e9l\u00e9rer la maintenance des files.',
                        helpFaq12Q: 'Comment fonctionnent les vues enregistr\u00e9es pour les filtres r\u00e9currents?',
                        helpFaq12A: 'Toute combinaison de filtres avanc\u00e9s peut \u00eatre enregistr\u00e9e comme vue nomm\u00e9e. Les \u00e9quipes peuvent les rouvrir instantan\u00e9ment pour suivre des d\u00e9partements, des files en retard ou des charges sp\u00e9cifiques coordinateur.',
                        helpFaq13Q: 'Comment les notes internes sont-elles s\u00e9par\u00e9es des r\u00e9ponses stagiaires?',
                        helpFaq13A: 'Les notes internes sont stock\u00e9es dans la m\u00eame timeline de candidature mais marqu\u00e9es priv\u00e9es. Elles sont visibles uniquement pour les coordinateurs/admins et ne sont jamais envoy\u00e9es aux stagiaires.',
                        helpFaq14Q: 'Peut-on utiliser des permissions bas\u00e9es sur les r\u00f4les entre \u00e9quipes?',
                        helpFaq14A: 'Oui. Les admins peuvent contr\u00f4ler les capacit\u00e9s coordinateurs, restreindre les actions sensibles et d\u00e9limiter les acc\u00e8s par r\u00f4le ou groupe pour garder des op\u00e9rations coh\u00e9rentes et s\u00e9curis\u00e9es.',
                        helpFaq15Q: 'Comment fonctionne le routage prioritaire des stagiaires?',
                        helpFaq15A: 'Les conditions de priorit\u00e9 peuvent d\u00e9clencher des surcharges d\'urgence, des groupes de routage sp\u00e9cifiques et des notifications personnalis\u00e9es afin que les candidatures prioritaires re\u00e7oivent un traitement plus rapide.',
                        helpFaq16Q: 'Peut-on personnaliser les champs de candidature dans le portail?',
                        helpFaq16A: 'Les admins peuvent configurer les champs visibles, les obligations, les contr\u00f4les d\u00e9partement/programme, les exigences t\u00e9l\u00e9phone et les valeurs par d\u00e9faut depuis les param\u00e8tres du portail.',
                        helpFaq17Q: 'Que se passe-t-il si aucun coordinateur n\'est disponible \u00e0 la soumission de candidature?',
                        helpFaq17A: 'La candidature reste non assign\u00e9e, l\'intention de routage est conserv\u00e9e et les admins sont notifi\u00e9s imm\u00e9diatement pour r\u00e9soudre les manques de couverture sans perdre le contexte.',
                        helpFaq18Q: 'Comment fonctionnent les pr\u00e9f\u00e9rences de notification par coordinateur?',
                        helpFaq18A: 'Chaque coordinateur peut configurer les \u00e9v\u00e9nements qu\'il re\u00e7oit. Les notifications sont regroup\u00e9es par type et date, avec des vues d\u00e9di\u00e9es aux retards pour un triage rapide.',
                        helpFaq19Q: 'Les \u00e9quipes peuvent-elles exporter les donn\u00e9es pour audits et revues de direction?',
                        helpFaq19A: 'Oui. Les listes de candidatures, vues de performance et rapports de d\u00e9partement peuvent \u00eatre export\u00e9s en CSV ou PDF pour la gouvernance mensuelle, la planification et la conformit\u00e9.',
                        helpFaq20Q: 'Comment le chatbot passe-t-il \u00e0 la cr\u00e9ation de candidature?',
                        helpFaq20A: 'Si le chatbot ne peut pas r\u00e9soudre apr\u00e8s le nombre de tours configur\u00e9, il propose un passage guid\u00e9 vers la cr\u00e9ation de candidature en conservant le contexte pour \u00e9viter au stagiaire de tout ressaisir.',
                    },
                };
                return dict[this.lang]?.[key] ?? key;
            },

            init() {
                /* Sync dark class on <html> whenever darkMode changes */
                this._watchDark();
            },

            _watchDark() {
                /* Alpine.effect runs reactively whenever darkMode changes */
                Alpine.effect(() => {
                    document.documentElement.classList.toggle('dark', this.darkMode);
                });
            },
        });
    });
</script>

{{ $slot }}
